server:
    port: 8082
    context-path: /
spring:
    zipkin:
      baseUrl: http://localhost:9411
      enabled: true
logging:
    level:
      org.springframework.web.servlet.DispatcherServlet: DEBUG
