server:
    port: 8081
    context-path: /
spring:
    zipkin:
      baseUrl: http://localhost:9411
      enabled: true
    cloud:
        stream:
          kafka:
            binder:
              brokers: localhost:9092
              zk-nodes: localhost:2181
logging:
    level:
      org.springframework.web.servlet.DispatcherServlet: DEBUG
