server:
    port: 8080
    context-path: /
spring:
    zipkin:
      baseUrl: http://localhost:9411
      enabled: true
    sleuth:
      keys:
        http:
          headers:
logging:
    level:
      org.springframework.web.servlet.DispatcherServlet: DEBUG
